### ISSUE TITLE
Data Model example

### ISSUE THREAD

**Issue by objectiveSee** [Oreoz/ember-vertical-timeline#11]
Hello! I'd love to use this component but I am not sure how to set up the data model. Do you have an example which shows how to hook up this component to your data? I do not understand whether `timeline.block` is reserved/required by your component, or whether `block` expects to have certain properties defined.

I am also not sure how to get the default styling working (as I'm pretty new to Ember). Thanks!

**Comment by Oreoz** [comment]
I just added a more concrete example to the dummy application (see #12 for reference). It should give you a pretty good idea of how you would go about hooking up data to the timeline itself.

The `timeline.block` component is definitely required in order to build a timeline with elements in it as this is the component where you define the contents of each block if that makes sense.

As far a getting the default styling to work, you'll need `ember-cli-sass` in your project as you need to compile the stylesheet that's exported. Then you simply import it inside of your application's main stylesheet. See https://github.com/Oreoz/ember-vertical-timeline/blob/master/tests/dummy/app/styles/app.scss.

Thanks!

**Comment by objectiveSee** [comment]
This looks great. Thank you! 🎊
